sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=DEBUG -DWITH_EXAMPLES=1 -DWITH_TESTS=1 ..
script:
  - make
  - cd deploy/tests
  - ./ngrestjsontest
  - ./test_server_client
